### ISSUE TITLE
GHC 7.4,7.6,7.10 build failures

### ISSUE THREAD

**Issue by bergmark** [k-bx/protocol-buffers#1]
The latest release doesn't build on GHC 7.10 (and dropped support for 7.4 and 7.6) , http://matrix.hackage.haskell.org/package/protocol-buffers#GHC-7.10/protocol-buffers-2.0.17

**Comment by bergmark** [comment]
I just queued builds for hprotoc and -descriptor as well, may take a while before the builder gets to it.

**Comment by k-bx** [comment]
@bergmark thanks for reporting! I'm adding travis for different GHCs, will try to fix things up.

Also, I never worked with hackage build-matrix. Will check it out. So far I can't even see matrix for latest release (2.1.0).

**Comment by bergmark** [comment]
It's currently building highlighting-kate against a new hashable so it's pretty clogged and it won't do a cabal update until that's done.

For the record only trustees can queue new builds, feel free to ping me about it.

**Comment by bergmark** [comment]
The build (finally) ran for the latest version, on 7.10:

```
Text/ProtocolBuffers/Identifiers.hs:124:24:
    Ambiguous occurrence ‘uncons’
    It could refer to either ‘Text.ProtocolBuffers.Identifiers.uncons’,
                             defined at Text/ProtocolBuffers/Identifiers.hs:103:3
                          or ‘Data.List.uncons’,
                             imported from ‘Data.List’ at Text/ProtocolBuffers/Identifiers.hs:33:1-16
                             (and originally defined in ‘GHC.List’)
```

**Comment by bergmark** [comment]
And the other two packages failed because they have protocol-buffers as a dependency.

**Comment by snoyberg** [comment]
This is causing trouble for Stackage too.

**Comment by k-bx** [comment]
Fixed GHC 7.10 https://travis-ci.org/k-bx/protocol-buffers/builds/69730426

**Comment by bergmark** [comment]
Indeed! http://matrix.hackage.haskell.org/package/protocol-buffers#GHC-7.6/protocol-buffers-2.1.1 Thanks @k-bx.

Do you intend to support older GHCs as well or should we put a lower bound on base?

**Comment by k-bx** [comment]
@bergmark initially I thought only keeping ghc >= 7.8 support and wait for requests for older ones, then I considered your issue-report as a request for older GHCs and decided to take a look at older ones.

So, current plan: take a closer look at older GHCs when I'll get back home in Kyiv (in a week) and think on how hard would it be. Seems not very trivial from first look, but I'm sure it can be handled with some CPP.

Also, do you use/need older GHCs or did you just post an issue after looking at build-matrix?

**Comment by bergmark** [comment]
Because of build-matrix + I mistakenly thought your release broke backwards compat but that happened earlier.

My goal is simply for the version bounds to reflect reality.

**Comment by k-bx** [comment]
@bergmark pushed `base >= 4.7.0` requirement for now, but will keep this issue opened for a while.
