### ISSUE TITLE
is template haskell necessary in generated code?

### ISSUE THREAD

**Issue by wavewave** [k-bx/protocol-buffers#14]
Generated haskell code from `hprotoc` contains TemplateHaskell language extension pragma and I doubt this is necessary. 

This is relevant for me since I am now developing an application on ARM machine using ghc cross compiler and ghc as cross compiler can not support Template Haskell. Although one can delete the pragma by hand, I think it is desirable to have it only when necessary.

**Comment by k-bx** [comment]
@wavewave I'm not sure regarding the need of TH there (since I'm not the author), but I have no opinion against removing it. Would you care to make a PR?

**Comment by wavewave** [comment]
I've made a pull request #15 for this. Thanks!

**Comment by k-bx** [comment]
@wavewave thank you!
