### ISSUE TITLE
Build failure when compiling Stackage Nightly

### ISSUE THREAD

**Issue by snoyberg** [k-bx/protocol-buffers#18]
Full build log at: https://gist.github.com/snoyberg/2e4f5016538963861030

**Comment by k-bx** [comment]
@snoyberg forgot to upload fixes from yesterday to hackage, now should be good.

P.s.: is there a way I can see latest nightly build logs to confirm they build fine after you make an issue? Would really help to have "last confirmation point". If there isn't – can I help somehow? I see build-instructions for nightly package set, maybe I could try setting up some public build-service.

**Comment by snoyberg** [comment]
You can look in the stackage-nightly repo to see if your package is included. We don't upload the build logs anywhere.

**Comment by k-bx** [comment]
@snoyberg will try to set up a nightly build somewhere. Thank you!

**Comment by snoyberg** [comment]
I'm still seeing same version of hprotoc on Hackage, so this problem persists. I'm going to have to disable hprotoc for a few days now until things get in order, we've had too many broken builds recently due to it.

**Comment by k-bx** [comment]
@snoyberg my upload of all 3 packages went fine, but hackage shows only protocol-buffers package in new version. When I try to upload one of other two – I get an error which says "probably it's already uploaded". I will contact hackage administrators to figure out what's the problem. Sorry for all this.

```
➜  protocol-buffers git:(master) stack upload ./descriptor
Getting file list for /Users/kb/workspace/protocol-buffers/descriptor/
Building sdist tarball for /Users/kb/workspace/protocol-buffers/descriptor/
Checking package 'protocol-buffers-descriptor' for common mistakes
Package check reported the following warnings:
The 'synopsis' field is rather long (max 80 chars is recommended).
'ghc-options: -O2' is rarely needed. Check that it is giving a real benefit and not just imposing longer compile times on your users.
'ghc-prof-options: -auto-all' is fine during development, but not recommended in a distributed package.
Uploading protocol-buffers-descriptor-2.1.10.tar.gz... forbidden upload
Usually means: you've already uploaded this package/version combination
Ignoring error and continuing, full message from Hackage below:

Error: Upload failed

This version of the package has already been uploaded.

As a matter of policy we do not allow package tarballs to be changed after a release (so we can guarantee stable md5sums etc). The usual recommendation is to upload a new version, and if necessary blacklist the existing one. In extraordinary circumstances, contact the administrators.
```

**Comment by k-bx** [comment]
@snoyberg hackage works somewhat unstable, I had to try multiple releases until getting a successful one, but it should now be good for 2.1.12, all three packages got uploaded.
