### ISSUE TITLE
Support multiple files using the same package

### ISSUE THREAD

**Issue by charleslaw** [k-bx/protocol-buffers#20]
Protobuf supports having multiple files use the same package, but this doesn't work with hprotoc - the output is `package_name.hs`.

The way the Python & C++ compilers work, they strip `.proto` from the filename & use that for the basename of the output file, as opposed to using the package name.

Python:
https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/python/python_generator.cc#L88

C++:
https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_generator.cc#L102

This might require setting a flag to keep backwards compatibility (--ignore-package-name).

These 2 files might make a good test:

a.proto:
```
package Test;
message A{
    required string name=1;
}
```

b.proto:
```
package Test;
import "a.proto";
message B{
    required A a=1;
}
```

**Comment by wavewave** [comment]
`hprotoc` already supports import and multiple files. When I run
```
hprotoc a.proto b.proto
```
I have `Test/A.hs` 

```
...
module Test.A (A(..)) where
import Prelude ((+), (/))
import qualified Prelude as Prelude'
import qualified Data.Typeable as Prelude'
import qualified Data.Data as Prelude'
import qualified Text.ProtocolBuffers.Header as P'

data A = A{name :: !(P'.Utf8)}
       deriving (Prelude'.Show, Prelude'.Eq, Prelude'.Ord, Prelude'.Typeable, Prelude'.Data\
)
...
```
and `Test/B.hs`
```
...
module Test.B (B(..)) where
import Prelude ((+), (/))
import qualified Prelude as Prelude'
import qualified Data.Typeable as Prelude'
import qualified Data.Data as Prelude'
import qualified Text.ProtocolBuffers.Header as P'
import qualified Test.A as Test (A)

data B = B{a :: !(Test.A)}
       deriving (Prelude'.Show, Prelude'.Eq, Prelude'.Ord, Prelude'.Typeable, Prelude'.Data\
)
...
```

Note that B correctly imported Test.A. I wonder if something is missing here?

**Comment by clawconduce** [comment]
My mistake, I must have had something wrong with my setup, and I can't recreate :/
