### ISSUE TITLE
skipping optional fields

### ISSUE THREAD

**Issue by charleslaw** [k-bx/protocol-buffers#26]
Sorry if this is the wrong place for this - I did not see a mailing list.  Also, I am new to Haskell, so I may be missing something fundamental.

I wanted to know if there is a way to skip specifying an optional field when creating protobuf message.  I am working with proto files that sometimes have 10+ fields where only 1 or 2 are set.  Also, fields like this can get added at any time, and I'd like it if those changes did not require a code update.

A little more detail here: https://codereview.stackexchange.com/questions/118180/haskell-zmq-protobuf-message-forwarding

**Comment by qrilka** [comment]
Hi @charleslaw  - I have answered you question on codereview.stackexchange.com 
Could we close this issue if my answer is good enough?

**Comment by clawconduce** [comment]
Thanks!
