### ISSUE TITLE
Implement map syntax from V2 language reference

### ISSUE THREAD

**Issue by luminaut** [k-bx/protocol-buffers#29]
Map syntax appears in the [language reference](https://developers.google.com/protocol-buffers/docs/proto#maps) but does not appear to be supported by this library. We may be able to implement and PR if this isn't planned work already.

**Comment by dfoxfranke** [comment]
@k-bx, what are your plans around this issue? I see that there are two open pull requests, #32 and #33, that implement map support. Do you intend to merge either of them?

**Comment by k-bx** [comment]
@dfoxfranke I do intent to merge one of them indeed, but unfortunately have not much time reviewing them thoughtfully. I will try to do that today or on weekend. It would be helpful if you would review them as well and share your thoughts if you have any :) Thanks

**Comment by tvh** [comment]
Done in https://github.com/k-bx/protocol-buffers/pull/97
