### ISSUE TITLE
[request] NFData instances

### ISSUE THREAD

**Issue by fosskers** [k-bx/protocol-buffers#40]
Hi there, in attempting to benchmark the different protobuf libraries, I noticed this library is missing `NFData` instances for its types. This prevents one from using `nf` when writing `criterion` benchmarks, which is necessary to gauge how long decoding from protobuf bytes actually takes.

Would it be possible to add these? Thank you kindly.

**Comment by k-bx** [comment]
Sure. Not sure if and when I'll get my hands on this, so PRs are welcome!

**Comment by fosskers** [comment]
It looks like the auto-generated types have `Generic` instances, so at least local to my benchmarks I could `derive instance NFData Foo` for the time being.

**Comment by fosskers** [comment]
That doesn't seem to work afterall. Deriving of `NFData` for this lib's `ExtField` fails.
