### ISSUE TITLE
Build failure with haskell-src-exts 1.18

### ISSUE THREAD

**Issue by snoyberg** [k-bx/protocol-buffers#45]
```
> /tmp/stackage-build8$ stack unpack hprotoc-2.4.0
Unpacked hprotoc-2.4.0 to /tmp/stackage-build8/hprotoc-2.4.0/
> /tmp/stackage-build8/hprotoc-2.4.0$ runghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb Setup configure --package-db=clear --package-db=global --package-db=/var/stackage/work/builds/nightly/pkgdb --libdir=/var/stackage/work/builds/nightly/lib --bindir=/var/stackage/work/builds/nightly/bin --datadir=/var/stackage/work/builds/nightly/share --libexecdir=/var/stackage/work/builds/nightly/libexec --sysconfdir=/var/stackage/work/builds/nightly/etc --docdir=/var/stackage/work/builds/nightly/doc/hprotoc-2.4.0 --htmldir=/var/stackage/work/builds/nightly/doc/hprotoc-2.4.0 --haddockdir=/var/stackage/work/builds/nightly/doc/hprotoc-2.4.0 --flags=
Configuring hprotoc-2.4.0...
> /tmp/stackage-build8/hprotoc-2.4.0$ runghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb Setup build
Building hprotoc-2.4.0...
Preprocessing library hprotoc-2.4.0...
[ 1 of 13] Compiling Text.ProtocolBuffers.ProtoCompile.Identifiers ( Text/ProtocolBuffers/ProtoCompile/Identifiers.hs, dist/build/Text/ProtocolBuffers/ProtoCompile/Identifiers.o )
[ 2 of 13] Compiling Text.ProtocolBuffers.ProtoCompile.BreakRecursion ( Text/ProtocolBuffers/ProtoCompile/BreakRecursion.hs, dist/build/Text/ProtocolBuffers/ProtoCompile/BreakRecursion.o )
[ 3 of 13] Compiling Text.ProtocolBuffers.ProtoCompile.Gen ( Text/ProtocolBuffers/ProtoCompile/Gen.hs, dist/build/Text/ProtocolBuffers/ProtoCompile/Gen.o )

Text/ProtocolBuffers/ProtoCompile/Gen.hs:77:8: error:
    Not in scope: type constructor or class ‘SrcLoc’
```

**Comment by ChrisKuklewicz** [comment]
Thanks, I will look into this.

**Comment by k-bx** [comment]
@ChrisKuklewicz I've started some time ago, but it turned out to be a multi-day work for haskell-src-exts. Please tell if you'll start and if you'll feel confidence weather you can finish this. I am still planning to do this otherwise, just not sure when.

**Comment by crockeea** [comment]
What's the status of a fix for this bug?

**Comment by k-bx** [comment]
@crockeea I wasn't working on this yet, not sure about anyone else.

**Comment by onethirtyfive** [comment]
I'm trying to build hprotoc 2.4.2 on nixos. Since I'm using the package definition from the nixpkgs repo (which is based on what's in hackage), it's trying to use `>= 1.16.0` for `haskell-src-exts`. I get the following:

```
[ 6 of 13] Compiling Text.ProtocolBuffers.ProtoCompile.Gen ( Text/ProtocolBuffers/ProtoCompile/Gen.hs, dist/build/Text/ProtocolBuffers/ProtoCompile/Gen.o )

Text/ProtocolBuffers/ProtoCompile/Gen.hs:77:8: error:
    Not in scope: type constructor or class ‘SrcLoc’
```

I'm a haskell noob, but I guess my best option is to fork this repo and find a way to get nix to use my version with `haskell-src-exts >= 1.16.0 && < 1.18`.

I wish I had the skills to help fix the code, but could this be fixed with a basic `haskell-src-exts` version constraint?

Thanks for your work on this library. :)

**Comment by k-bx** [comment]
@onethirtyfive it could be, yes, just try that out in all the cabal-files and if it helps – I'd merge it

**Comment by onethirtyfive** [comment]
I forked nixpkgs, changed the version on a branch, and then had my local install use that version instead. It compiled without a hitch. idk if you're a nixos person, but here's my PR:

https://github.com/onethirtyfive/nixpkgs/pull/1/files

Changing it to 1.17.1 did the trick. Seems like a semver violation to make a breaking API change between 1.17.1 -> 1.18. Womp womp.

In any case, adding a version constraint to `1.17.1` appears to fix the problem. I'll submit a PR.
