### ISSUE TITLE
hprotoc is not campatible with haskell-src-exts-1.20

### ISSUE THREAD

**Issue by Shimuuar** [k-bx/protocol-buffers#55]
Could you please amend upper bound on hackage since package fails to build unless you specify constraint manually? 1.19 works

**Comment by k-bx** [comment]
@Shimuuar thanks for spotting! Uploaded as 2.4.6, let's keep an issue open in case someone wants to actually add the 1.20 compatibility

**Comment by Shimuuar** [comment]
Just for your information. You can edit version ranges in place without uploading.

**Comment by k-bx** [comment]
@Shimuuar is there a documentation explaining how to do that? I can't find one.

**Comment by k-bx** [comment]
@Shimuuar sorry, found it, it's right at the package's page in "maintainer's corner"

**Comment by tvh** [comment]
This is done rigght?
