### ISSUE TITLE
Call for a maintainer

### ISSUE THREAD

**Issue by k-bx** [k-bx/protocol-buffers#64]
Hey everyone,

Looking back, I feel like this is a point where I need to call for a maintainer of this repo. I initially imported the code from an abandoned state and moved it into GitHub because I was using it together with the `riak` package, I was mostly doing a minimum amount of work needed to keep it build under new GHC releases.

This package needs a maintainer who has time to:

- make a proper test-suite, or at least some, since currently it's quite absent
- make a thoughtful dive into the architecture and be able to make decisions wisely and carefuly
- go through all the issues and PRs

Really hoping to get a person who can do this, at least partially. Thanks!

**Comment by tvh** [comment]
Hey,

I think I could help with this. We rely fairly heavily on this package and also currently maintain a fork for deriving JSON and omitting some instances. It would be great to get this work merged back so that we don't have to do this anymore.

**Comment by k-bx** [comment]
Sounds fantastic, I'll pass the needed rights tomorrow. @tvh please tell me your hackage username

**Comment by tvh** [comment]
http://hackage.haskell.org/user/TvH

**Comment by tmcgilchrist** [comment]
Hey,

Happy to help out on this too if you need a second person. I’m using riak
and protobufs for a few things as well.

http://hackage.haskell.org/user/lambda_foo

**Comment by sjking** [comment]
I'm happy to help especially with respect to making a proper test suite. We use this library extensively. http://hackage.haskell.org/user/sjking

**Comment by k-bx** [comment]
@tvh I've added you as a maintainer and a collaborator. Please put yourself in the cabal file as the main maintainer. 

@tmcgilchrist @sjking thank you for the responses, and especially for the proper test suite proposal. I think a regular parcitipation in PRs/Issue discussions should be enough for now (without the maintainer rights). @tvh please tell if you'd like to organize the test suite yourself or if @sjking should do one (probably a good idea to make a separate issue/PR).

Thanks again everyone!

**Comment by tvh** [comment]
@k-bx I just tried to update the info on hackage but you only added me as a maintainer for `protocol-buffers` and not for `protocol-buffers-descriptor` and `hprotoc`.

**Comment by k-bx** [comment]
@tvh oops, added
