### ISSUE TITLE
Does not build under windows. (old-time dependency)

### ISSUE THREAD

**Issue by ruffianeo** [k-bx/protocol-buffers#72]
Cabal fails to install hprotoc on windows due to a failing dependency names old-time.
Suggesting to remove that dependency as that package appears to be unix specific (shell script during build!).
Even the name says its "old" and there is no reason for platform specific code in this project. And yes - some of us windows dudes refuse to install cygwin or mingw....

**Configuring old-time-1.1.0.3...
cabal.exe: The package has a './configure' script. If you are on Windows, This
requires a Unix compatibility toolchain such as MinGW+MSYS or Cygwin. If you
are not on Windows, ensure that an 'sh' command is discoverable in your path.](url)**

**Comment by tvh** [comment]
I wasn't aware that hprotoc doesn't build on windows. I had to look up what the depencency actually is and this is how it is pulled in:
```
"hprotoc" -> "haskell-src-exts" -> "cpphs" -> "old-time"
```
haskell-src-exts is a hard dependency and I imagine it needs cpphs as well. I think https://github.com/malcolmwallace/cpphs/issues/15 is the real issue here.

**Comment by tvh** [comment]
Closed as there is a new release of cpphs
