### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by k-bx** [k-bx/protocol-buffers#74]
I've noticed that hprotoc received fixes for GHC 8.6 but wasn't released, would appreciate if someone would do that.

I will then add it back on stackage to make it into [LTS 13](https://www.stackage.org/blog/2018/11/upcoming-lts-13-ghc-8-6-2)

**Comment by k-bx** [comment]
@tvh would you make one please?

**Comment by tvh** [comment]
Sure.

**Comment by tvh** [comment]
New release is out as 2.4.12

**Comment by k-bx** [comment]
👍 thanks!
