### ISSUE TITLE
defaultUserHooks in Setup.hs is deprecated

### ISSUE THREAD

**Issue by romanofski** [k-bx/protocol-buffers#89]
I've come across a problem compiling protocol-buffers on modern Fedora versions which ship Cabal 3.0.1.0 in which the following deprecation warning:

```
+ ghc --make -package Cabal -no-user-package-db -dynamic Setup
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )
Setup.hs:2:29: warning: [-Wdeprecations]
    In the use of `defaultUserHooks'
    (imported from Distribution.Simple):
    Deprecated: "Use simpleUserHooks or autoconfUserHooks, unless you need Cabal-1.2
             compatibility in which case you must stick with defaultUserHooks"
  |
2 | main = defaultMainWithHooks defaultUserHooks
  |              
```
from https://download.copr.fedorainfracloud.org/results/romanofski/gtfsschedule/fedora-32-x86_64/01720512-ghc-protocol-buffers/build.log.gz (Cabal 2.4.0.1) turns into an error: https://download.copr.fedorainfracloud.org/results/romanofski/gtfsschedule/fedora-33-x86_64/01720512-ghc-protocol-buffers/build.log.gz (Cabal 3.0.1.0).

I apologize for my laziness not to do the whole fork/create pull request dance for a one liner. I've attached the patch to this issue. It helped me to get protocol-buffers compiling again: https://copr.fedorainfracloud.org/coprs/romanofski/gtfsschedule/build/1730467/

[0001-Fix-Cabal-Setup-deprecation-error.patch.txt](https://github.com/k-bx/protocol-buffers/files/5468422/0001-Fix-Cabal-Setup-deprecation-error.patch.txt)

**Comment by k-bx** [comment]
@romanofski thanks! Released as 2.4.14
