### ISSUE TITLE
protocol-buffers-descriptor is super slow and memory-intensive to build with 8.10.2

### ISSUE THREAD

**Issue by jberryman** [k-bx/protocol-buffers#91]
- building without fiddling results in OOM (I have 8gb RAM) at building `Text.DescriptorProtos.FileOptions`
- switching to `-O1` and removing `fspec-constr-count` doesn't seem to help
- adding `-O0` to just the `FileOptions` module gets me past that, by now it's stuck on `Text.DescriptorProtos.FieldDescriptorProto` (though memory is around 4GB)

With `O0` on the whole project I can build quickly. I'm not sure what the proper remedy is here.

I wonder if this would make a decent GHC ticket.

**Comment by k-bx** [comment]
Oh wow, confirming this on macOS.

**Comment by tvh** [comment]
Yes, I also experienced this but didn't bother to debug so thanks for that!

I created the GHC-Ticket https://gitlab.haskell.org/ghc/ghc/-/issues/18923

**Comment by tvh** [comment]
I managed to do a workaround in #94 which is released as  2.4.17.

**Comment by jberryman** [comment]
Really appreciate it!
